name: Action tgbot

on:
  push:
    branches:
      - main

jobs:
  deploy-fastapi:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run FastAPI
      env: 
        DEBUG: "0"
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        MAI_TOKEN: ${{ secrets.MAI_TOKEN }}
        PROBIUS_TOKEN: ${{ secrets.PROBIUS_TOKEN }}
      run: nohup python -m uvicorn main:app --port 7710 --host 0.0.0.0 >> ./fastapi.log 2>&1 &

  deploy-tgbot:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run TG bot
      env: 
        DEBUG: "0"
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        MAI_TOKEN: ${{ secrets.MAI_TOKEN }}
        PROBIUS_TOKEN: ${{ secrets.PROBIUS_TOKEN }}
      run: nohup python -u activate_bot.py >> ./tgbot.log 2>&1 &