name: Action tgbot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Building docker image and run container
      env: 
        IMAGE_NAME: "tgbot_dispatch_image"
        CONTAINER_NAME: "tgbot_dispatch"
        DEBUG: "0"
        MAI_TOKEN: ${{ secrets.MAI_TOKEN }}
        DEEPSEEK_APIKEY: ${{ secrets.DEEPSEEK_APIKEY }}
        FISH_AUDIO_APIKEY: ${{ secrets.FISH_AUDIO_APIKEY }}
      run: |
        sudo docker stop $CONTAINER_NAME && sudo docker rm -f $CONTAINER_NAME || true
        sudo docker build --progress=plain -t $IMAGE_NAME .
        sudo docker run --network host -d --name $CONTAINER_NAME \
          -e DEBUG=$DEBUG \
          -e MAI_TOKEN=$MAI_TOKEN \
          -e DEEPSEEK_APIKEY=$DEEPSEEK_APIKEY \
          -e FISH_AUDIO_APIKEY=$FISH_AUDIO_APIKEY \
          $IMAGE_NAME
        sudo docker image prune -f
        sudo docker rm $(docker ps -q -f status=exited) || true
