name: Action tgbot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Building docker image and run container
      env: 
        IMAGE_NAME: "tgbot_dispath_image"
        CONTAINER_NAME: "tgbot_dispath"
        DEBUG: "0"
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        MAI_TOKEN: ${{ secrets.MAI_TOKEN }}
        PROBIUS_TOKEN: ${{ secrets.PROBIUS_TOKEN }}
        OPENAI_SB_API_KEY: ${{ secrets.OPENAI_SB_API_KEY }}
      run: |
        sudo docker rm -f $IMAGE_NAME || true
        sudo docker build --progress=plain -t $IMAGE_NAME .
        sudo docker run -d -p 7710:8000 --name $CONTAINER_NAME \
          -e DEBUG=$DEBUG \
          -e TG_CHAT_ID=$TG_CHAT_ID \
          -e MAI_TOKEN=$MAI_TOKEN \
          -e PROBIUS_TOKEN=$PROBIUS_TOKEN \
          -e OPENAI_SB_API_KEY=$OPENAI_SB_API_KEY \
          $IMAGE_NAME
        sudo docker image prune -f
        sudo docker rm $(docker ps -q -f status=exited) || true
